# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      r: release
    - os: linux
      dist: precise
      r: devel

    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: release
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: devel

    - os: osx
      osx_image: xcode8.1
      r: release

    - os: osx
      r: release
